extraction:
  cpp:
    after_prepare: 
      - python report.py 1
  cobol:
    after_prepare: 
      - python report.py 1
  csharp:
    after_prepare: 
      - python report.py 1
  java:
    after_prepare: 
      - python report.py 1
  javascript:
    after_prepare: 
      - python report.py 1
  python:
    after_prepare: 
      - python report.py 1
